// Gerçek saha soruları (Sprint 7, madde 10) — AI ekranındaki "Örnek
// Sorular" listesi ve tests/aiRecommendation.test.ts bu dosyadan beslenir.
// En az 50 madde olması istendi; kapsam TEDAŞ/EPDK/TEİAŞ/Resmî Gazete/
// TSE/IEC şartname-yönetmelik-standart konularının tamamını dolaşır.
export const EXAMPLE_QUESTIONS: readonly string[] = [
  '2 km uzaktaki OG hattan branşman alınacak. Hangi şartnameler okunmalı?',
  'Yeni beton köşk yapılacak, hangi teknik şartnameler geçerli?',
  'XLPE kablo seçilecek, hangi standartlara bakmalıyım?',
  'Trafo merkezi kurulacak, hangi dokümanlar gerekli?',
  'Topraklama ölçümü yapılacak, hangi yönetmeliğe göre?',
  'OG ring şebeke kurulacak, hangi hücre şartnamesi geçerli?',
  'Direk tipi seçimi nasıl yapılır?',
  'Parafudr seçimi için hangi şartname geçerli?',
  'Kompanzasyon yapılacak, hangi ekipman şartnamesi gerekli?',
  'Kesici seçimi nasıl yapılır?',
  'Sayaç panosu kurulacak, hangi şartname geçerli?',
  'AG dağıtım panosu kurulumu için hangi şartname geçerli?',
  'Enerji nakil hattı (ENH) projesi için hangi yönetmelik geçerli?',
  'Kablo başlığı montajı nasıl yapılır?',
  'Ek muf (kablo eki) hangi şartnameye göre yapılır?',
  'Ayırıcı seçimi için hangi teknik şartname geçerli?',
  'Sigorta seçimi nasıl yapılır, hangi standart geçerli?',
  'Ölçü trafosu (akım/gerilim trafosu) seçimi nasıl yapılır?',
  'Yeni bağlantı talebi için hangi EPDK yönetmeliği geçerli?',
  'Bağlantı anlaşması süreci nasıl işler?',
  'Sistem kullanım anlaşması için hangi mevzuata bakmalıyım?',
  'Bağlantı görüşü ne kadar sürede verilir?',
  'Geçici kabul için hangi işlemler yapılmalı?',
  'Kesin kabul süreci nasıl işler?',
  'Yeraltı kablosu döşenirken hangi şartname geçerli?',
  'Havai hat kurulumunda hangi standart geçerli?',
  'İzolatör seçimi (post/askı tipi) nasıl yapılır?',
  'Travers seçimi için hangi şartname geçerli?',
  'Beton direk kırılma yükü sınıfı nasıl belirlenir?',
  'Demir (çelik) direk ne zaman kullanılır?',
  'Hizmet kalitesi göstergeleri (kesinti süresi) nasıl hesaplanır?',
  'Kesinti bildirimi hangi sürede yapılmalı?',
  'Tüketici şikayeti için hangi EPDK yönetmeliği geçerli?',
  'Dokunma gerilimi sınırı ne kadar olmalı?',
  'Adım gerilimi hesabı nasıl yapılır?',
  'Kaçak akım koruma cihazı hangi standarda göre seçilir?',
  'IP koruma sınıfı nasıl belirlenir?',
  'IK darbe koruma sınıfı nedir?',
  'Yıldırımdan korunma sistemi nasıl tasarlanır?',
  'Trafo merkezi topraklama tasarımı nasıl yapılır?',
  'Arc-flash (ark patlaması) riski nasıl hesaplanır?',
  'Harmonik distorsiyon sınırları nelerdir?',
  'Gerilim kalitesi (flicker, harmonik) hangi standarda göre ölçülür?',
  'SCADA/uzaktan izleme ekipmanı hangi protokolle çalışmalı?',
  'Dağıtık üretim (güneş/rüzgar) şebekeye nasıl bağlanır?',
  'İletken kesiti seçimi nasıl yapılır?',
  'ACSR iletken kopma yükü nasıl hesaplanır?',
  'Hat bağlantı donanımı (klemens, ek manşonu) nasıl seçilir?',
  'İç tesisat projesi hangi yönetmeliğe göre çizilir?',
  'Gerilim düşümü sınırı yüzde kaçtır?',
  'Aydınlatma direği rüzgar yükü hesabı nasıl yapılır?',
  'Genel aydınlatma uygulama esasları nelerdir?',
  'Elektrik tesisleri kabul yönetmeliği neyi kapsar?',
  'Yapı denetimi ile elektrik tesisatı ilişkisi nedir?',
  'Enerji kimlik belgesi elektrik tesisatını nasıl etkiler?',
  'İşyerlerinde elektrik İSG kuralları nelerdir?',
  'Enerjili çalışma yaklaşma mesafeleri nedir?',
  'Elektrik tesislerinin işletilmesi kuralları nelerdir?',
  'Periyodik bakım hangi sıklıkla yapılmalı?',
  'Arıza müdahale süresi ne kadar olmalı?',
  'Reaktif güç ve güç kalitesi kriterleri nelerdir?',
  'Şebeke yönetmeliği hangi bağlantı kriterlerini kapsar?',
  'OG/YG bağlantı teknik kriterleri nelerdir?',
  'Koruma-koordinasyon çalışması nasıl yapılır?',
  'Dağıtım şirketi lisans yükümlülükleri nelerdir?',
  'Elektrik piyasası kanunu neyi düzenler?',
  'Enerji verimliliği mevzuatı nelere uygulanır?',
  'Kayıp-kaçak bedeli nasıl hesaplanır?',
] as const;
