// src/catalogs/conductors — merkezi ACSR iletken kataloğu.
//
// ⚠️ Bu, uygulamadaki TEK iletken veri kaynağıdır (bkz. README.md).
// Sayılar, Sprint 2A'da OG Akım Taşıma Kapasitesi motoru için aktarılan
// değerlerle BİREBİR AYNIDIR (hiçbir sayı değiştirilmemiştir):
//   - HAWK, ampacityCondition3A = 740 A → Excel'den doğrudan doğrulanmıştır.
//   - SWALLOW, ampacityCondition1A = 120 A → Excel'den doğrudan doğrulanmıştır.
//   - RAVEN, reactance35kVOhmPerKm = 0,387 Ω/km → Excel'den doğrudan doğrulanmıştır.
// Geri kalan alanlar gerçek ACSR üretici tablolarından (Priority Wire ACSR
// #4020-03, Nexans AWG serisi) türetilmiş mühendislik tahminidir — bu
// yüzden hepsi `sourceStatus: 'pendingBookVerification'` olarak
// işaretlenmiştir (bkz. src/calculations/engines/ampacityOG/data.ts'in
// önceki başlık notu ve modules/calculations/README.md).
import type { ACSRConductor } from './types.ts';

export const ACSR_CONDUCTORS: readonly ACSRConductor[] = [
  {
    id: 'swallow',
    code: 'SWALLOW',
    name: 'Swallow',
    standardName: 'Swallow — 3 AWG',
    awgMcm: '3 AWG',
    aluminumAreaMm2: 26.69,
    steelAreaMm2: 4.45,
    totalAreaMm2: 31.14,
    nominalDiameterMm: 7.14,
    nominalWeightKgPerM: 0.1078,
    breakingLoadKg: 1042,
    elasticityInitialKgPerMm2: 6500,
    elasticityFinalKgPerMm2: 7900,
    linearExpansionCoefficient: 0.0000193,
    resistance20OhmPerKm: 1.055,
    reactance10kVOhmPerKm: 0.372,
    reactance35kVOhmPerKm: 0.409,
    equivalentCuMm2: 16.28,
    ampacityCondition1A: 120,
    ampacityCondition2A: 163,
    ampacityCondition3A: 174,
    notes: 'ampacityCondition1A (120 A) Excel kaynağından doğrudan doğrulanmıştır; diğer alanlar mühendislik tahminidir.',
    sourceStatus: 'pendingBookVerification',
  },
  {
    id: 'raven',
    code: 'RAVEN',
    name: 'Raven',
    standardName: 'Raven — 1/0 AWG',
    awgMcm: '1/0 AWG',
    aluminumAreaMm2: 53.54,
    steelAreaMm2: 8.92,
    totalAreaMm2: 62.46,
    nominalDiameterMm: 10.11,
    nominalWeightKgPerM: 0.2158,
    breakingLoadKg: 1987,
    elasticityInitialKgPerMm2: 6500,
    elasticityFinalKgPerMm2: 7900,
    linearExpansionCoefficient: 0.0000193,
    resistance20OhmPerKm: 0.522,
    reactance10kVOhmPerKm: 0.350,
    reactance35kVOhmPerKm: 0.387,
    equivalentCuMm2: 32.66,
    ampacityCondition1A: 187,
    ampacityCondition2A: 254,
    ampacityCondition3A: 272,
    notes: 'reactance35kVOhmPerKm (0,387 Ω/km) Excel kaynağından doğrudan doğrulanmıştır; diğer alanlar mühendislik tahminidir.',
    sourceStatus: 'pendingBookVerification',
  },
  {
    id: 'pigeon',
    code: 'PIGEON',
    name: 'Pigeon',
    standardName: 'Pigeon — 3/0 AWG',
    awgMcm: '3/0 AWG',
    aluminumAreaMm2: 84.98,
    steelAreaMm2: 14.16,
    totalAreaMm2: 99.14,
    nominalDiameterMm: 12.75,
    nominalWeightKgPerM: 0.3437,
    breakingLoadKg: 3003,
    elasticityInitialKgPerMm2: 6500,
    elasticityFinalKgPerMm2: 7900,
    linearExpansionCoefficient: 0.0000193,
    resistance20OhmPerKm: 0.328,
    reactance10kVOhmPerKm: 0.336,
    reactance35kVOhmPerKm: 0.373,
    equivalentCuMm2: 51.84,
    ampacityCondition1A: 244,
    ampacityCondition2A: 331,
    ampacityCondition3A: 354,
    notes: 'Bu iletken için Excel kaynağından doğrudan doğrulanmış bir değer yoktur; tüm alanlar gerçek ACSR üretici tablolarından türetilmiş mühendislik tahminidir.',
    sourceStatus: 'pendingBookVerification',
  },
  {
    id: 'partridge',
    code: 'PARTRIDGE',
    name: 'Partridge',
    standardName: 'Partridge — 266.8 MCM',
    awgMcm: '266.8 MCM',
    aluminumAreaMm2: 135.14,
    steelAreaMm2: 22.03,
    totalAreaMm2: 157.17,
    nominalDiameterMm: 16.31,
    nominalWeightKgPerM: 0.5462,
    breakingLoadKg: 5048,
    elasticityInitialKgPerMm2: 5700,
    elasticityFinalKgPerMm2: 6800,
    linearExpansionCoefficient: 0.0000198,
    resistance20OhmPerKm: 0.209,
    reactance10kVOhmPerKm: 0.320,
    reactance35kVOhmPerKm: 0.357,
    equivalentCuMm2: 82.44,
    ampacityCondition1A: 367,
    ampacityCondition2A: 499,
    ampacityCondition3A: 533,
    notes: 'Bu iletken için Excel kaynağından doğrudan doğrulanmış bir değer yoktur; tüm alanlar gerçek ACSR üretici tablolarından türetilmiş mühendislik tahminidir.',
    sourceStatus: 'pendingBookVerification',
  },
  {
    id: 'hawk',
    code: 'HAWK',
    name: 'Hawk',
    standardName: 'Hawk — 477 MCM',
    awgMcm: '477 MCM',
    aluminumAreaMm2: 241.50,
    steelAreaMm2: 39.33,
    totalAreaMm2: 280.83,
    nominalDiameterMm: 21.79,
    nominalWeightKgPerM: 0.9763,
    breakingLoadKg: 8845,
    elasticityInitialKgPerMm2: 5700,
    elasticityFinalKgPerMm2: 6800,
    linearExpansionCoefficient: 0.0000198,
    resistance20OhmPerKm: 0.117,
    reactance10kVOhmPerKm: 0.302,
    reactance35kVOhmPerKm: 0.339,
    equivalentCuMm2: 147.32,
    ampacityCondition1A: 509,
    ampacityCondition2A: 692,
    ampacityCondition3A: 740,
    notes: 'ampacityCondition3A (740 A) Excel kaynağından doğrudan doğrulanmıştır; diğer alanlar mühendislik tahminidir.',
    sourceStatus: 'pendingBookVerification',
  },
];
